#!/usr/bin/with-contenv bash

if [ ! -f "/keylock" ]; then
    cd /etc/xrdp
    xrdp-keygen xrdp
    rm -f /etc/xrdp/*.pem
    openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
    -keyout /etc/xrdp/key.pem \
    -out /etc/xrdp/cert.pem \
    -subj "/C=US/ST=CA/L=Carlsbad/O=Linuxserver.io/OU=LSIO Server/CN=*"
    touch /keylock
fi
