#!/usr/bin/with-contenv bash

# default file copies first run
[[ ! -f /config/startwm ]] && \
	cp /defaults/startwm.sh /config/startwm.sh

# permissions
PERM=$(stat -c '%U' /config/.config)
[[ "${PERM}" != "abc" ]] && \
        chown -R abc:abc /config
